# Clean up
---
- name: Remove redundant packages
  community.general.portage:
    package: "{{ item }}"
    state: absent
  vars:
    ansible_python_interpreter: "{{ gentoo_prefix_path }}/usr/bin/python3"
  with_items: "{{ prefix_remove_packages }}"
