# Clean up
---
- name: Remove redundant packages
  community.general.portage:
    package: "{{ item }}"
    state: absent
  with_items: "{{ prefix_remove_packages }}"

- name: Remove intermediate build packages
  community.general.portage:
    depclean: true
    withbdeps: false

 
