# Install a specified list of sets and packages.
---
- name: Install package set {{ package_sets }}
  community.general.portage:
    package: "@{{ item }}"
    state: present
  vars:
    ansible_python_interpreter: "{{ gentoo_prefix_path }}/usr/bin/python3"
  with_items: "{{ package_sets }}"
  tags:
    - set

- name: Install additional packages
  community.general.portage:
    package: "{{ item }}"
    state: present
  vars:
    ansible_python_interpreter: "{{ gentoo_prefix_path }}/usr/bin/python3"
  with_items: "{{ prefix_packages }}"
